algoritmo "Exercicio 3"
//Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
var
nome: caractere
salario: real
inicio
Escreva("Qual o nome do funcionário? ")
Leia(nome)
Escreva("Qual seu salário? ")
Leia(salario)
Escreva("O funcionário ", nome, " tem um salário de R$", salario)
fimalgoritmo