algoritmo "Exercicio 11"
//Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta.
var
A: real
B: real
C: real
delta: real
inicio
Escreva("Digite o valor de A: ")
Leia(A)
Escreva("Digite o valor de B: ")
Leia(B)
Escreva("Digite o valor de C: ")
Leia(C)
delta<-(b^2)-(4*A*C)
Escreva("O valor de delta é: ", delta, ".")
fimalgoritmo