algoritmo "Exercicio 5"
//Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5
var
N1, N2: real
media: real
inicio
Escreva("Digite a primeira nota: ")
Leia(N1)
Escreva("Digite a segunda nota: ")
Leia(N2)
media<-(n1+n2)/2
Escreva("A média ente ", N1, " e ", N2, " é igual a ", media, ".")
fimalgoritmo