algoritmo "Exercicio 42"
//Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!
var
C, N: Inteiro
inicio
      Escreva ("Digite um número inteiro positivo: ")
      Leia (N)
      C <- 0
      Repita
            Escreval (C)
            C <- c + 1
      Ate (C > N)

fimalgoritmo