algoritmo "Exercicio 7"
//Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666
var
N: real
dob: real
ter: real
inicio
Escreva("Digite um número: ")
Leia(N)
dob<-N*2
ter<-N/3
Escreval("O dobro de ", N, " é ", dob, ".")
Escreva("A terca parte de ", N, " é ", ter, ".")
fimalgoritmo