algoritmo "Exercicio 4"
//Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.
var
N1, N2: inteiro
soma: inteiro
inicio
Escreva("Digite um número: ")
Leia(N1)
Escreva("Digite outro número: ")
Leia(N2)
soma<-N1+N2
Escreva("A soma ente ", N1, " e ", N2, " é igual a ", soma, ".")
fimalgoritmo